---
- name: Upgrade
  hosts: all
  strategy: free
  become: true
  force_handlers: true
  vars:
    update_grub_to_grub_2: true
  tasks:
    # - name: Install leapp packages
    #   ansible.builtin.package:
    #     name: leapp-upgrade
    #     state: latest # noqa package-latest
    #   when: false

    - name: Perform OS upgrade
      ansible.builtin.import_role:
        name: infra.leapp.upgrade
...
