---
# Set which Ansible Collection to use for the Linux System Roles.
# For community/upstream, use 'fedora.linux_system_roles'
# For the RHEL System Roles, use 'redhat.rhel_system_roles'
# - fedora.linux_system_roles
# - redhat.rhel_system_roles
# infra_leapp_upgrade_system_roles_collection: redhat.rhel_system_roles
infra_leapp_upgrade_system_roles_collection: fedora.linux_system_roles
...
