---
- name: leapp_newest_kernel_not_in_use | Boot to latest kernel
  block:
    - name: leapp_newest_kernel_not_in_use | Get list of installed kernels packages sorted by the newest version
      ansible.builtin.shell: |
        set -o pipefail
        sudo rpm -q kernel --queryformat '%{version}-%{release}.%{arch}\n' | sort -Vr
      register: installed_kernels
      changed_when: true

    - name: leapp_newest_kernel_not_in_use | Set default kernel to latest
      ansible.builtin.command: grubby --set-default /boot/vmlinuz-{{ installed_kernels.stdout_lines[0] }}
      register: set_default_kernel
      changed_when: set_default_kernel.rc == 0

    - name: leapp_newest_kernel_not_in_use | Update-and-reboot | Reboot when updates applied
      ansible.builtin.reboot:
        reboot_timeout: "{{ reboot_timeout }}"
        post_reboot_delay: "{{ post_reboot_delay }}"
      timeout: "{{ reboot_timeout }}"

...
