---
- name: disable-previous-repo-files | Backup repo files
  ansible.builtin.copy:
    remote_src: true
    src: "/etc/yum.repos.d/{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}.{{ ansible_date_time.iso8601_basic_short }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ __repo_files }}"

- name: disable-previous-repo-files | Remove repo files
  ansible.builtin.file:
    path: "/etc/yum.repos.d/{{ item }}"
    state: absent
  loop: "{{ __repo_files }}"

...
