---
# post_upgrade_release: "8.8"
# leapp_upgrade_opts: '--target 8.8'

satellite_organization: my_org
satellite_activation_key: rhel{{ ansible_distribution_major_version }}_dev
satellite_activation_key_pre_leapp: "{{ satellite_activation_key }}"
satellite_activation_key_leapp: "{{ satellite_activation_key }}"
satellite_activation_key_post_leapp: "{{ satellite_activation_key }}"

...
